[env:esp32dev]
platform                = espressif32
board                   = esp32dev
framework               = arduino
monitor_speed           = 115200
upload_speed            = 115000
board_build.flash_mode  = dio

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
  adafruit/Adafruit BusIO
  adafruit/Adafruit BME280 Library
  adafruit/Adafruit Unified Sensor
  bblanchon/ArduinoJson